/*
  hbridge.h - converts the signals for step/direction that are generated by grbl to signals for phase-type (quadratic? sinusoidal?) stepper drivers.

  Copyright (c) 2012 Tom Vollerthun (vollerthun@gmx.de)

  Grbl is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Grbl is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Grbl.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef hbridge_h
#define hbridge_h

#include "nuts_bolts.h"

/**
 * Convert the given pattern from step/direction style
 * to phase-style pattern.
 * To correctly change from one phase to the next, 
 * the given pattern will be kept as state.
 * 
 */
uint8_t toHbridge(uint8_t stepDirPattern);

#endif